# Generated by Django 2.1.3 on 2018-11-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.PositiveSmallIntegerField()),
                ('version_id', models.PositiveSmallIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('workflow_location', models.FilePathField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='workflow',
            unique_together={('workflow_id', 'version_id')},
        ),
    ]
